[project]
name = "ficopilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hei", email = "peiyu4150@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langgraph>=1.2.11",
    "pydantic>=2.13.4",
]

[project.scripts]
ficopilot = "ficopilot:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]
